sql:
  host: 127.0.0.1
  port: 3306
  database: battlebox
  username: root
  password: password
  table_prefix: bb_


arena:
  team1:
    x: 69.0
    y: 69.0
    z: 69.0
    block: "BLUE_WOOL"
  team2:
    x: -69.0
    y: 69.0
    z: -69.0
    block: "RED_WOOL"
  world: "battlebox"

  center:
    block: "GOLD_BLOCK"

kits:
  archer:
    name: "Archer"
    description: "pew pew shooty bow"
    items:
      - "BOW:1"
      - "ARROW:64"
      - "GOLDEN_APPLE:32"
    icon: "BOW"
    armor:
      - "DIAMOND_HELMET"
      - "DIAMOND_CHESTPLATE"
      - "DIAMOND_LEGGINGS"
      - "DIAMOND_BOOTS"

  swordsman:
    name: "Swordsman"
    description: "swish swish stabby sword"
    items:
      - "DIAMOND_SWORD:1"
      - "GOLDEN_APPLE:32"
    armor:
        - "DIAMOND_HELMET"
        - "DIAMOND_CHESTPLATE"
        - "DIAMOND_LEGGINGS"
        - "DIAMOND_BOOTS"
    icon: "DIAMOND_SWORD"