name: BattleBox
version: '${project.version}'
main: uk.jamieisgeek.battlebox.BattleBox
api-version: 1.19
commands:
  battlebox:
    aliases: bb
    description: BattleBox test command

  battleboxadmin:
    aliases: bba
    description: BattleBox admin command